### ISSUE TITLE
Unable to get access token: 401 Bad Credentials

### ISSUE THREAD

**Issue by HkB115** [openmhealth/omh-dsu-ri#20]
Hello,
I have tried setting this up on both a debian and ubuntu server, both giving me the same end result.
I have docker, docker-compose, and docker-machine installed and working properly. I added the rows to the database and checked to make sure that the client has the correct details and the user does as well. However, when I try to get the access token using postman, it gives back a 401 bad credentials error. I have looked at the other issues on here and none of their solutions fixed my problem. Any help would be greatly appreciated.

**Comment by sophieroos** [comment]
Hi, I'm still having this issue. I used the Postman repository, first created the user, and using the same credentials to get the token.
I'm getting this response:
`{
    "timestamp": "2019-02-19T14:23:03.891+0000",
    "status": 401,
    "error": "Unauthorized",
    "message": "Bad credentials",
    "path": "/oauth/token"
}`
